"""Operator-rationale evidence provider: reads previously supplied local rationale.

Reads revision-bound, operator-authored rationale for specific files from
``.archex/history-evidence/rationale/`` -- a manifest recording the git
revision it was written against plus a JSON list of ``{target_path,
rationale, author, recorded_at}`` entries. Rationale is never inferred or
generated by archex; an operator writes it out of band and this provider
only reads it.
"""

from __future__ import annotations

import datetime as _dt
import json
from pathlib import Path
from typing import cast

from archex.integrations.history.models import (
    HistoryEvidenceProviderName,
    HistoryProviderReceipt,
    OperatorRationale,
    ProviderAvailability,
)

_MANIFEST_FILENAME = "manifest.json"
_RATIONALE_FILENAME = "rationale.json"
_DEFAULT_EVIDENCE_DIRNAME = ".archex/history-evidence/rationale"


def _now_iso() -> str:
    return _dt.datetime.now(tz=_dt.UTC).isoformat()


class OperatorRationaleProvider:
    """Reads pre-supplied operator-authored rationale."""

    def __init__(self, evidence_dir: Path | str | None = None) -> None:
        self._evidence_dir = Path(evidence_dir) if evidence_dir is not None else None

    @property
    def name(self) -> HistoryEvidenceProviderName:
        return HistoryEvidenceProviderName.OPERATOR_RATIONALE

    def _resolve_evidence_dir(self, repo_root: Path) -> Path:
        if self._evidence_dir is not None:
            return self._evidence_dir
        return repo_root / _DEFAULT_EVIDENCE_DIRNAME

    def probe(self, repo_root: Path, *, expected_revision: str) -> HistoryProviderReceipt:
        evidence_dir = self._resolve_evidence_dir(repo_root)
        manifest_path = evidence_dir / _MANIFEST_FILENAME
        rationale_path = evidence_dir / _RATIONALE_FILENAME
        if not manifest_path.is_file() or not rationale_path.is_file():
            return HistoryProviderReceipt(
                provider=self.name,
                availability=ProviderAvailability.UNAVAILABLE,
                reason=f"no operator rationale found at {evidence_dir}",
                expected_revision=expected_revision,
                collected_at=_now_iso(),
            )
        try:
            manifest = json.loads(manifest_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            return HistoryProviderReceipt(
                provider=self.name,
                availability=ProviderAvailability.UNAVAILABLE,
                reason=f"could not read rationale manifest at {manifest_path}: {exc}",
                expected_revision=expected_revision,
                collected_at=_now_iso(),
            )
        observed_revision = str(manifest.get("revision") or "") or None
        if not observed_revision:
            return HistoryProviderReceipt(
                provider=self.name,
                availability=ProviderAvailability.UNAVAILABLE,
                reason=f"rationale manifest at {manifest_path} has no revision",
                expected_revision=expected_revision,
                collected_at=_now_iso(),
            )
        if observed_revision != expected_revision:
            return HistoryProviderReceipt(
                provider=self.name,
                availability=ProviderAvailability.STALE,
                reason=(
                    f"operator rationale was recorded at revision {observed_revision[:12]}, "
                    f"current revision is {expected_revision[:12]}"
                ),
                expected_revision=expected_revision,
                observed_revision=observed_revision,
                collected_at=_now_iso(),
            )
        return HistoryProviderReceipt(
            provider=self.name,
            availability=ProviderAvailability.AVAILABLE,
            expected_revision=expected_revision,
            observed_revision=observed_revision,
            collected_at=_now_iso(),
        )

    def collect(
        self, repo_root: Path, *, expected_revision: str
    ) -> tuple[list[OperatorRationale], HistoryProviderReceipt]:
        probe_receipt = self.probe(repo_root, expected_revision=expected_revision)
        if probe_receipt.availability != ProviderAvailability.AVAILABLE:
            return [], probe_receipt

        evidence_dir = self._resolve_evidence_dir(repo_root)
        rationale_path = evidence_dir / _RATIONALE_FILENAME
        try:
            raw_entries: object = json.loads(rationale_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            return [], HistoryProviderReceipt(
                provider=self.name,
                availability=ProviderAvailability.STALE,
                reason=f"could not read rationale file at {rationale_path}: {exc}",
                expected_revision=expected_revision,
                observed_revision=probe_receipt.observed_revision,
                collected_at=_now_iso(),
            )
        if not isinstance(raw_entries, list):
            return [], HistoryProviderReceipt(
                provider=self.name,
                availability=ProviderAvailability.STALE,
                reason=f"rationale file at {rationale_path} is not a JSON list",
                expected_revision=expected_revision,
                observed_revision=probe_receipt.observed_revision,
                collected_at=_now_iso(),
            )

        entries_raw = cast("list[object]", raw_entries)
        entries: list[OperatorRationale] = []
        for raw_item in entries_raw:
            if not isinstance(raw_item, dict):
                continue
            raw_entry = cast("dict[str, object]", raw_item)
            target_path = raw_entry.get("target_path")
            rationale_text = raw_entry.get("rationale")
            recorded_at = raw_entry.get("recorded_at")
            if not target_path or not rationale_text or not recorded_at:
                continue
            author = raw_entry.get("author")
            entries.append(
                OperatorRationale(
                    target_path=str(target_path),
                    rationale=str(rationale_text),
                    author=str(author) if author else None,
                    recorded_at=str(recorded_at),
                    revision=expected_revision,
                )
            )

        receipt = HistoryProviderReceipt(
            provider=self.name,
            availability=ProviderAvailability.AVAILABLE,
            expected_revision=expected_revision,
            observed_revision=probe_receipt.observed_revision,
            records_collected=len(entries),
            collected_at=_now_iso(),
        )
        return entries, receipt
