"""CompatibilityArtifact: a per-release, evidence-linked compatibility + benchmark bundle (M9).

Bundles archex's own installed version, supported Python range, and report/
index schema versions with SOURCE's dimensioned `StatusCard` (M9's
documentation/release evidence) and a pointer to the checked-in external
benchmark evidence, when present under SOURCE, into one read-only artifact
suitable for attaching to a GitHub release alongside the built wheel/sdist.

Never fabricates a benchmark reference: `benchmark_evidence_path` is
populated only when a real, previously committed benchmark manifest is
found under SOURCE; it is `None` (not a guessed or default path) otherwise.
"""

from __future__ import annotations

import importlib.metadata as importlib_metadata
import json
import time
from pathlib import Path

from pydantic import BaseModel, model_validator

from archex import __version__
from archex.api import index_repository
from archex.config import load_config, load_index_config
from archex.models import RepoSource
from archex.report.artifact import REPORT_SCHEMA_VERSION
from archex.report.status_card import StatusCard, build_status_card

COMPATIBILITY_ARTIFACT_SCHEMA_VERSION = "1.0.0"

#: Conventional path, relative to the analyzed repository root, of the
#: checked-in external head-to-head benchmark manifest. Referenced, never
#: regenerated by this module -- benchmark runs stay their own explicit
#: `archex benchmark ...` invocation.
_BENCHMARK_MANIFEST_PATH = "benchmarks/headtohead/results/manifest.yaml"

_CLIENT_COMPATIBILITY_MATRIX_PATH = "docs/CLIENT_COMPATIBILITY_MATRIX.md"


class CompatibilityArtifactError(ValueError):
    """Raised when a compatibility artifact cannot be built."""


class CompatibilityArtifact(BaseModel):
    """The canonical, read-only per-release compatibility + benchmark artifact.

    Every field is a verifiable local fact: an installed package version, a
    schema version string read from the built index, or a path to a
    previously committed document -- never a live claim about anything
    external (PyPI availability, CI run status, or a benchmark result not
    already checked into the repository).
    """

    schema_version: str = COMPATIBILITY_ARTIFACT_SCHEMA_VERSION
    archex_version: str
    python_requires: str
    report_schema_version: str
    index_schema_version: str
    compatibility_matrix_path: str
    benchmark_evidence_path: str | None = None
    status_card: StatusCard
    generated_at: str

    @model_validator(mode="after")
    def _validate_artifact(self) -> CompatibilityArtifact:
        if not self.archex_version.strip():
            raise ValueError("archex_version must not be empty")
        if not self.python_requires.strip():
            raise ValueError("python_requires must not be empty")
        if not self.report_schema_version.strip():
            raise ValueError("report_schema_version must not be empty")
        if not self.index_schema_version.strip():
            raise ValueError("index_schema_version must not be empty")
        if not self.compatibility_matrix_path.strip():
            raise ValueError("compatibility_matrix_path must not be empty")
        return self

    def to_json(self) -> str:
        return json.dumps(self.model_dump(mode="json"), indent=2, sort_keys=True)


def _python_requires() -> str:
    try:
        value: str | None = importlib_metadata.metadata("archex")["Requires-Python"]
    except importlib_metadata.PackageNotFoundError:
        return "unknown"
    return value or "unknown"


def build_compatibility_artifact(source: str | Path) -> CompatibilityArtifact:
    """Build the per-release compatibility + benchmark evidence artifact for SOURCE."""
    repo_root = Path(source).expanduser().resolve()
    repo_source = RepoSource(local_path=str(source))
    config = load_config(repo_source)
    index_config = load_index_config(repo_source)

    store = index_repository(repo_source, config=config, index_config=index_config)
    try:
        index_schema_version = store.get_metadata("schema_version") or ""
    finally:
        store.close()

    if not index_schema_version:
        raise CompatibilityArtifactError(f"index at {repo_root} has no recorded schema_version")

    status_card = build_status_card(source)

    benchmark_manifest = repo_root / _BENCHMARK_MANIFEST_PATH
    benchmark_evidence_path = _BENCHMARK_MANIFEST_PATH if benchmark_manifest.is_file() else None

    return CompatibilityArtifact(
        archex_version=__version__,
        python_requires=_python_requires(),
        report_schema_version=REPORT_SCHEMA_VERSION,
        index_schema_version=index_schema_version,
        compatibility_matrix_path=_CLIENT_COMPATIBILITY_MATRIX_PATH,
        benchmark_evidence_path=benchmark_evidence_path,
        status_card=status_card,
        generated_at=str(time.time()),
    )
